version: '3.1'

services:

  mongo:
    image: mongo:jammy
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongotest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
