services:
  typesense:
    image: typesense/typesense:28.0
    container_name: typesense_server
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'